cloud:
  aws:
    credentials:
      instance-profile: true
      use-default-aws-credentials-chain: true
    region:
      auto: true
    stack:
      auto: false
management:
  metrics:
    export:
      cloudwatch:
        enabled: true


bucketName: cloudcafe-app





---

spring:
  profiles: dev

cloud:
  aws:
    credentials:
      access-key: AKIAX6PELHF2IA26QRV3
      secret-key: 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
      instance-profile: false
    region:
      static: us-west-2
    stack:
      auto: false
management:
  metrics:
    export:
      cloudwatch:
        enabled: false
