cloud:
  aws:
    credentials:
      instance-profile: true
      use-default-aws-credentials-chain: true
    region:
      auto: true
    stack:
      auto: false
management:
  metrics:
    export:
      cloudwatch:
        enabled: true


bucketName: cloudcafe-app





---

spring:
  profiles: dev

cloud:
  aws:
    credentials:
      access-key: #accesskey
      secret-key: #accessSecreat
      instance-profile: false
    region:
      static: #us-west-2
    stack:
      auto: false
management:
  metrics:
    export:
      cloudwatch:
        enabled: false
